/**
 * APPSYNC License Decryptor
 *
 * Node.js script to decrypt .lic files generated by APPSYNC.
 *
 * Usage:
 *   node decrypt-license.cjs <path-to-file.lic>
 *
 * Example:
 *   node decrypt-license.cjs APPSYNC-APP-M1ABC123.lic
 *
 * This will output the decrypted license JSON including:
 *   - user_id
 *   - email
 *   - hardware_id  (SHA-256 hash of cpuId|macAddress|diskSerial)
 *   - max_client
 *   - license_key
 *   - product
 *   - type
 *   - issued_at
 */

const fs = require('fs')
const path = require('path')
const crypto = require('crypto')

// ─── Must match the secret in license-crypto.js ───
const LICENSE_SECRET = 'SnapDesk-LicenseKey-Secret-2026!!'

/**
 * Derive AES-256 key from secret (SHA-256 of the secret string).
 */
function deriveKey() {
  return crypto.createHash('sha256').update(LICENSE_SECRET).digest()
}

/**
 * Decrypt a .lic buffer → original JSON object.
 *
 * File format: [16-byte IV] + [AES-256-GCM ciphertext + 16-byte auth tag]
 */
function decryptLicense(buffer) {
  const key = deriveKey()
  const iv = buffer.slice(0, 16)
  const encrypted = buffer.slice(16)

  // AES-GCM: last 16 bytes = auth tag
  const authTag = encrypted.slice(encrypted.length - 16)
  const ciphertext = encrypted.slice(0, encrypted.length - 16)

  const decipher = crypto.createDecipheriv('aes-256-gcm', key, iv)
  decipher.setAuthTag(authTag)

  let plaintext = decipher.update(ciphertext)
  plaintext = Buffer.concat([plaintext, decipher.final()])

  return JSON.parse(plaintext.toString('utf-8'))
}

/**
 * Generate hardware_id from components (for verification).
 */
function generateHardwareId(cpuId, macAddress, diskSerial) {
  const raw = [cpuId, macAddress, diskSerial].join('|')
  return crypto.createHash('sha256').update(raw).digest('hex')
}

// ─── CLI ─────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2)

  if (args.length === 0) {
    console.log('')
    console.log('╔══════════════════════════════════════════════════╗')
    console.log('║       APPSYNC License Decryptor v1.0            ║')
    console.log('╚══════════════════════════════════════════════════╝')
    console.log('')
    console.log('Usage:')
    console.log('  node decrypt-license.cjs <file.lic>')
    console.log('')
    console.log('Options:')
    console.log('  --verify <cpuId> <macAddress> <diskSerial>')
    console.log('    Verify hardware_id matches the given hardware components')
    console.log('')
    console.log('Examples:')
    console.log('  node decrypt-license.cjs APPSYNC-APP-M1ABC123.lic')
    console.log(
      '  node decrypt-license.cjs license.lic --verify BFEBFBFF000906A3 00:1A:2B:3C:4D:5E WD-WMC4N0123456',
    )
    console.log('')
    process.exit(0)
  }

  const filePath = path.resolve(args[0])

  if (!fs.existsSync(filePath)) {
    console.error(`❌ File not found: ${filePath}`)
    process.exit(1)
  }

  const buffer = fs.readFileSync(filePath)

  console.log('')
  console.log('╔══════════════════════════════════════════════════╗')
  console.log('║       APPSYNC License Decryptor v1.0            ║')
  console.log('╚══════════════════════════════════════════════════╝')
  console.log('')
  console.log(`📄 File    : ${path.basename(filePath)}`)
  console.log(`📦 Size    : ${buffer.length} bytes`)
  console.log('')

  try {
    const data = decryptLicense(buffer)

    // Output pure JSON so server/tools can parse it directly
    console.log(JSON.stringify(data, null, 2))

    // --verify flag
    const verifyIdx = args.indexOf('--verify')
    if (verifyIdx !== -1 && args.length >= verifyIdx + 4) {
      const cpuId = args[verifyIdx + 1]
      const macAddress = args[verifyIdx + 2]
      const diskSerial = args[verifyIdx + 3]

      const computedHash = generateHardwareId(cpuId, macAddress, diskSerial)
      const verification = {
        verify: {
          cpu_id: cpuId,
          mac_address: macAddress,
          disk_serial: diskSerial,
          computed_hash: computedHash,
          license_hash: data.hardware_id,
          match: computedHash === data.hardware_id,
        },
      }
      console.log(JSON.stringify(verification, null, 2))
    }
  } catch (err) {
    console.error(JSON.stringify({ error: 'Decryption failed', message: err.message }))
    process.exit(1)
  }
}

main()
